# ==========================================
# 1. INPUT (Entrada de Dados)
# ==========================================
input {
  file {
    # Caminho onde o Logstash enxerga o seu access.log do Nginx dentro do container
    path => "/var/log/nginx/access.log"
    start_position => "beginning"
    sincedb_path => "/dev/null" # Força a ler desde o início sempre que reiniciar
  }
}

# ==========================================
# 2. FILTER (A Mágica da Transformação - Grok)
# ==========================================
filter {
  grok {
    # Esse padrão lê a linha padrão do Nginx e quebra em variáveis JSON
    match => { "message" => "%{IPORHOST:clientip} %{USER:ident} %{USER:auth} \[%{HTTPDATE:timestamp}\] \"%{WORD:method} %{DATA:url} HTTP/%{NUMBER:httpversion}\" %{NUMBER:status} %{NUMBER:bytes} \"%{DATA:referrer}\" \"%{DATA:user_agent}\"" }
  }

  # # Remove mensagens que falharem no filtro para não sujar nossa base de IA
  # if "_grokparsefailure" in [tags] {
  #   drop { }
  # }
}

# ==========================================
# 3. OUTPUT (Saída para o Elasticsearch)
# ==========================================
output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "projeto-nginx-brutos"
  }
  stdout { codec => rubydebug }
}